### ISSUE TITLE
Infrared materials

### ISSUE THREAD

**Issue by Jonas231** [mjhoptics/opticalglass#6]
Hi Michael,
concratulations nice package. I thought about a dash app and python for what you have done and just now found your package which almost leaves no wishes. 

Is there a way we could include material data such as infrared materials included in zemax special glass cataloge or in Code V? Would it make sense to translate the optical design code format txt files to an Excel format or should a python function directly parse the txt files and translate to dataframes?

Kind regards,
Jonas

**Comment by mjhoptics** [comment]
Hi Jonas,
Thanks for the kind words. I've thought about adding the Zemax glass file to opticalglass, but haven't gotten around to it. I've been able to use the RefractiveIndex.info data to cover the few special materials I seem to need (fused silica, CaF2, etc), so that has contributed to my lack of urgency. I believe most of the usual IR materials are available in that database so hopefully that's a viable workaround if you need something immediately.
I think the CODE V glass catalog is a binary file, so that's effectively out of reach for me. The Zemax file is text I believe, so it's within the realm of possibility.
Cheers,
Mike

**Comment by Jonas231** [comment]
Hello Michael,

I think Code V has xml files of the glass catalogues created from the original excels. This can be seen from the test version which includes the files.
There is also OpTaliX which provides (also in the test version) the special catalogue and other glass vendors' catalogues as csv convertible to xlsx being human readable. I should write a module which translates these tables to your data structure such that they can be included. This would help me a lot. 

I am interested in ZnSe, ZnS, Ge, the like...

Regards,
Jonas

**Comment by mjhoptics** [comment]
Hi Jonas,
Once you get the data into excel, including adding appropriate data headers, you can write a GlassPandas subclass to read the excel file into a structured pandas dataframe. Look at the existing catalogs like Hoya and Schott to see how the mapping is set up. The excel file is first read into a dataframe with the same row and column headers as the spreadsheet. With the excel files provided by the manufacturers, you can define the range of columns covered by, say, the dispersion coefficients by directly reading of the excel rows and columns, e.g. from the Hoya catalog:
```
            ('dispersion coefficients', None, 2, 'AC', 'AN'),
```
where the coefficients are between columns AC and AN; the coefficient labels are in row 2. For data like refractive indices or transmission, the values in the header row are typically wavelengths. The label is used across all catalogs and allows for common references to a subset of the data in each catalog. The mapping from the excel dataframe to the opticalglass dataframe doesn't modify the data at all, it just rearranges the row and column indices.

A note of caution about data sources. Data from different vendors is covered under more restrictive license agreements  than the `opticalglass` BSD-3 license. Probably ok for your own use but would need to understand licenses otherwise.

Regards,
Mike

**Comment by Jonas231** [comment]
Hi Michael,
okay I will do it. There are also cases when data is only provided only in zemax agf format, like in this case
of Schott IRG glasses:
https://www.schott.com/en-ae/products/ir-materials-p1000261/downloads

So it will make sens to write a agf Excel converter. It reads the txt files, converts them to np arrays, pandas dataframes and xlsx maybe in Schott format. 

Regards,
Jonas

**Comment by mjhoptics** [comment]
FWIW there is a bit of agf reading code in the [zemax.py](https://github.com/quartiq/rayopt/blob/master/rayopt/zemax.py) module of [rayopt](https://github.com/quartiq/rayopt). I don't know how complete an implementation it is, but it could be a good starting point. The zemax importer in [ray-optics](https://github.com/mjhoptics/ray-optics) started from the zemax converter in [rayopt](https://github.com/quartiq/rayopt).
HTH
Mike

**Comment by Jonas231** [comment]
Hi Michael,
I added an xlsx file of the Zemax agf catalogue in my fork "https://github.com/Jonas231/opticalglass/blob/master/src/opticalglass/data/infrared_2022.xlsx".
I created this file using https://github.com/nzhagen/zemaxglass/blob/master/ZemaxGlass.py with the file "https://github.com/Jonas231/opticalglass/blob/master/src/opticalglass/test_ZemaxGlass.py"

I added a GlassPandas subclass in https://github.com/Jonas231/opticalglass/blob/master/src/opticalglass/optical_glass_agf_class.py.

I try to setup a Glass catalogue in glass_dash.py](https://github.com/Jonas231/opticalglass/blob/master/src/opticalglass/glass_dash.py using 

# read new glass catalogue
import opticalglass.optical_glass_agf_class as agf
#import optical_glass_agf_class as agf
catalog = agf.Zemax_infrared_Catalog()

Now I get this error message:

Do you have an idea what could be the reason for this?

runfile('C:/Users/Jonas/opticalglass/src/opticalglass/glass_dash.py', wdir='C:/Users/Jonas/opticalglass/src/opticalglass')
Traceback (most recent call last):

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)

  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'CZ'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "C:\Users\Jonas\opticalglass\src\opticalglass\glass_dash.py", line 43, in <module>
    catalog = agf.Zemax_infrared_Catalog()

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\opticalglass-0.0.0-py3.8.egg\opticalglass\util.py", line 37, in __call__
    cls._instances[cls] = (super(Singleton, cls).

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\opticalglass-0.0.0-py3.8.egg\opticalglass\optical_glass_agf_class.py", line 159, in __init__
    super().__init__('infrared_2022', fname, series_mappings, item_mappings,

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\opticalglass-0.0.0-py3.8.egg\opticalglass\glass.py", line 303, in __init__
    self.df = build_glass_cat(xl_df, series_mappings, item_mappings,

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\opticalglass-0.0.0-py3.8.egg\opticalglass\glass.py", line 175, in build_glass_cat
    for idx in headers.loc[row].loc[col1:colk].index:

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexing.py", line 967, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexing.py", line 1180, in _getitem_axis
    return self._get_slice_axis(key, axis=axis)

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexing.py", line 1214, in _get_slice_axis
    indexer = labels.slice_indexer(slice_obj.start, slice_obj.stop, slice_obj.step)

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 6274, in slice_indexer
    start_slice, end_slice = self.slice_locs(start, end, step=step)

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 6490, in slice_locs
    end_slice = self.get_slice_bound(end, "right")

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 6403, in get_slice_bound
    raise err

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 6397, in get_slice_bound
    slc = self.get_loc(label)

  File "C:\Users\Jonas\.conda\envs\mypython38\lib\site-packages\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err

KeyError: 'CZ'


Best regards,
Jonas

**Comment by mjhoptics** [comment]
Jonas,
Happy New Year!
A couple of things.

1. The column range for the 10mm transmitted data should be from 'BA' to 'BM'
2. Since you're creating the spreadsheet yourself, there is no need to use a processing routine to convert header strings into wavelength values. (When point 1 is corrected, this is the next problem). Just put the wavelengths in the header row directly. Note that `opticalglass` is nanometer-centric (vs micrometer) for wavelengths.
HTH
Mike

**Comment by Jonas231** [comment]
Hi Michael,
a happy new year to you too!
Thank you for the hints.
I changed my original xlsx and the columns BA ... BM in the subclass.

I still get this error though:

  File "C:\Users\Jonas\opticalglass\src\opticalglass\optical_glass_agf_class.py", line 126, in get_transmission_wvl
    return float(header_str[len('TAUI10/'):])

TypeError: 'float' object is not subscriptable

My headers look like this:
![grafik](https://user-images.githubusercontent.com/38330725/210434561-a060ca8f-6377-475c-b744-9d4e1538fbd5.png)
(exactly as in the Schott.xls)

So I am not sure where the error comes from.

Regards,
Jonas

**Comment by mjhoptics** [comment]
I think the headers are being reformatted in some way. When I open the spreadsheet, I see 

<img width="106" alt="image" src="https://user-images.githubusercontent.com/33294031/210447983-7d937303-2820-42af-a66b-3cc57047eff8.png">

No matter, you don't have to follow the Schott convention. When you are creating the spreadsheet, just enter the wavelength values directly in the header row and use the following definition for the series_mapping:
```
('internal transmission mm, 10', None, header_row, 'BA', 'BM')
```
Mike

**Comment by mjhoptics** [comment]
OpticalGlass v2 supports IR materials via AGF files and the RefractiveIndex.Info library has a very broad selection of materials.
